AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Serverless Application Model template for Serverless Image Resizer for C# Lambda

Resources:  
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'ServerlessImageResizing::ServerlessImageResizing.Functions::Get'
      Runtime: dotnetcore2.0
      CodeUri: src/
      Description: 'Simple example that demonstrates how to resize images on-the-fly using Amazon API Gateway, AWS Lambda, and Amazon S3.' 
      Timeout: 30
      MemorySize: 256
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonS3FullAccess
      Environment:
        Variables:
          S3_BUCKET:
            Ref: S3Bucket
      Events:
        GetResource:
          Type: Api
           Properties:
            Path: /
            Method: GET
  
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-image-resizing
  
# Outputs: