version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in install
  pre_build:
    commands:
      - echo Installing dependencies - `pwd`
      - dotnet restore src/ServerlessImageResizing/ServerlessImageResizing.csproj
      - echo Dependencies install completed `date`
  build:
    commands:
      - echo Starting build `date` in `pwd`
      - cd src/ServerlessImageResizing && dotnet lambda package
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yaml

artifacts:
  type: zip
  files:
    - app-sam-export.yaml
  discard-paths: yes
